In [1]:
import numpy as np
# 生成随机数组
data = np.random.randn(2, 3)
data

array([[-0.19226477,  0.08809307, -1.06955932],
       [-1.407121  ,  1.13980271,  0.14592144]])

In [2]:
data * 10

array([[ -1.92264767,   0.88093067, -10.69559325],
       [-14.07121002,  11.39802709,   1.45921437]])

In [3]:
data + data

array([[-0.38452953,  0.17618613, -2.13911865],
       [-2.814242  ,  2.27960542,  0.29184287]])

In [4]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

4.1.1 生成ndarray

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int64')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2, 3, 2))

array([[[6.92803182e-310, 4.65889404e-310],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

4.1.2 ndarray的数据类型

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [20]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [21]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [22]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

4.1.3 NumPy数组算术

In [27]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
arr * 0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [33]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

4.1.4 基础索引和切片

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

5

In [37]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [42]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [43]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [44]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# 数组切片的拷贝而不是一份视图
arr_slice_copy = arr[5:8].copy()
arr_slice_copy

array([5, 6, 7])

In [46]:
arr_slice_copy = 12
arr_slice_copy
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [48]:
arr2d[0][2]

3

In [49]:
arr2d[0, 2]

3

In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1, 0]

array([7, 8, 9])

In [55]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [56]:
x[0]

array([7, 8, 9])

In [60]:
arr = np.array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [62]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [65]:
arr2d[1, :2]

array([4, 5])

In [66]:
arr2d[:2, 2]

array([3, 6])

In [67]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [68]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

4.1.5 布尔索引

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [70]:
data = np.random.randn(7, 4)
data

array([[-1.31450737, -0.80828735,  0.01234284, -0.45276316],
       [ 0.5526052 , -0.16005433,  0.38284534,  0.02845479],
       [ 0.7028923 ,  0.10947879, -0.40779056,  0.84951709],
       [-0.72960877, -0.84807434,  1.00367976,  1.10312736],
       [ 0.35231153, -0.76582528, -0.76235034,  0.087196  ],
       [ 1.02567108, -0.66292597, -0.24204122, -0.8225574 ],
       [ 0.85597932, -0.79177204, -0.25699263,  0.57493059]])

In [71]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [72]:
data[names == 'Bob']

array([[-1.31450737, -0.80828735,  0.01234284, -0.45276316],
       [-0.72960877, -0.84807434,  1.00367976,  1.10312736]])

In [73]:
data[names == 'Bob', 2:]

array([[ 0.01234284, -0.45276316],
       [ 1.00367976,  1.10312736]])

In [74]:
data[names == 'Bob', 3]

array([-0.45276316,  1.10312736])

In [75]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [76]:
data[~(names == 'Bob')]

array([[ 0.5526052 , -0.16005433,  0.38284534,  0.02845479],
       [ 0.7028923 ,  0.10947879, -0.40779056,  0.84951709],
       [ 0.35231153, -0.76582528, -0.76235034,  0.087196  ],
       [ 1.02567108, -0.66292597, -0.24204122, -0.8225574 ],
       [ 0.85597932, -0.79177204, -0.25699263,  0.57493059]])

In [77]:
cond = names == 'Bob'

In [78]:
data[~cond]

array([[ 0.5526052 , -0.16005433,  0.38284534,  0.02845479],
       [ 0.7028923 ,  0.10947879, -0.40779056,  0.84951709],
       [ 0.35231153, -0.76582528, -0.76235034,  0.087196  ],
       [ 1.02567108, -0.66292597, -0.24204122, -0.8225574 ],
       [ 0.85597932, -0.79177204, -0.25699263,  0.57493059]])

In [79]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [80]:
data[mask]

array([[-1.31450737, -0.80828735,  0.01234284, -0.45276316],
       [ 0.7028923 ,  0.10947879, -0.40779056,  0.84951709],
       [-0.72960877, -0.84807434,  1.00367976,  1.10312736],
       [ 0.35231153, -0.76582528, -0.76235034,  0.087196  ]])

In [83]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.01234284, 0.        ],
       [0.5526052 , 0.        , 0.38284534, 0.02845479],
       [0.7028923 , 0.10947879, 0.        , 0.84951709],
       [0.        , 0.        , 1.00367976, 1.10312736],
       [0.35231153, 0.        , 0.        , 0.087196  ],
       [1.02567108, 0.        , 0.        , 0.        ],
       [0.85597932, 0.        , 0.        , 0.57493059]])

In [84]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.5526052 , 0.        , 0.38284534, 0.02845479],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.02567108, 0.        , 0.        , 0.        ],
       [0.85597932, 0.        , 0.        , 0.57493059]])

4.1.6 神奇索引

In [86]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [87]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [88]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [89]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [91]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

4.1.7 数组转置和换轴

In [92]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [94]:
arr = np.random.randn(6,3)
arr

array([[ 0.501164  , -1.39311338, -0.29020311],
       [ 0.52828105, -0.57718349, -1.45589506],
       [-1.13132877,  0.96746481, -0.09143804],
       [-1.03040923,  1.46781527, -0.66030607],
       [-2.00340786,  0.18119586, -0.85846454],
       [-0.95757237, -0.22084313, -0.27789473]])

In [96]:
np.dot(arr.T,arr)

array([[ 7.80248208, -3.76160048,  1.85522976],
       [-3.76160048,  5.44597913,  0.09275492],
       [ 1.85522976,  0.09275492,  3.46240013]])

In [97]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [98]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [99]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [100]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])