In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.12222742, -1.93240558,  0.10316849, -0.58974165,  0.07222397,
        1.65031187, -0.30184007,  0.60971442])

In [5]:
y

array([-0.80161368,  0.52604965,  0.0606843 ,  0.79514224, -0.97309532,
       -1.05303058, -0.43174198,  0.80347539])

In [6]:
np.maximum(x, y)

array([-0.12222742,  0.52604965,  0.10316849,  0.79514224,  0.07222397,
        1.65031187, -0.30184007,  0.80347539])

In [7]:
arr = np.random.randn(7) * 5
arr

array([ 1.67300599, -5.40130088, -1.45281904,  3.57372815, -5.14353859,
       -0.07164705, -4.62886589])

In [8]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.67300599, -0.40130088, -0.45281904,  0.57372815, -0.14353859,
       -0.07164705, -0.62886589])

In [9]:
whole_part

array([ 1., -5., -1.,  3., -5., -0., -4.])

In [12]:
np.sqrt(arr)

/home/maxwell/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.29344733,        nan,        nan, 1.89043068,        nan,
              nan,        nan])

In [13]:
arr

array([ 1.67300599, -5.40130088, -1.45281904,  3.57372815, -5.14353859,
       -0.07164705, -4.62886589])

In [14]:
np.sqrt(arr, arr)

/home/maxwell/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.29344733,        nan,        nan, 1.89043068,        nan,
              nan,        nan])

In [15]:
arr

array([1.29344733,        nan,        nan, 1.89043068,        nan,
              nan,        nan])