In [1]:
import numpy as np
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points) # xs和ys是一样的
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [2]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [6]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

In [7]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

4.3.1 将条件逻辑作为数组操作

In [8]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [9]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [10]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [11]:
arr = np.random.randn(4, 4)
arr

array([[-0.69508667, -1.65706676,  0.42088291, -0.80545864],
       [ 0.58595012, -1.52065099,  0.6241636 ,  0.80998164],
       [-0.08158311,  0.5418083 ,  1.64878489,  0.93493402],
       [ 0.64440091,  0.72668386, -1.22094711, -0.43753208]])

In [12]:
arr > 0

array([[False, False,  True, False],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False]])

In [14]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2, -2],
       [ 2, -2,  2,  2],
       [-2,  2,  2,  2],
       [ 2,  2, -2, -2]])

In [15]:
np.where(arr > 0, 2, arr)

array([[-0.69508667, -1.65706676,  2.        , -0.80545864],
       [ 2.        , -1.52065099,  2.        ,  2.        ],
       [-0.08158311,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -1.22094711, -0.43753208]])

4.3.4 数学和统计方法

In [16]:
arr = np.random.randn(5, 4)
arr

array([[ 0.25820337, -1.17038655, -1.13135034, -0.16217645],
       [ 0.67919327, -1.20730958,  0.76487987,  0.20012436],
       [ 0.156083  , -0.71865924,  0.6246681 , -1.28341187],
       [-1.51663776,  0.42066002,  0.35873995, -0.20636212],
       [-0.53215914, -0.47396788,  0.55329079, -0.53592364]])

In [17]:
arr.mean()

-0.2461250912636251

In [18]:
np.mean(arr)

-0.2461250912636251

In [19]:
arr.sum()

-4.922501825272502

In [21]:
arr.mean(axis = 0)

array([-0.19106345, -0.62993265,  0.23404568, -0.39754994])

In [22]:
arr.mean(axis = 1)

array([-0.55142749,  0.10922198, -0.30533   , -0.23589998, -0.24718997])

In [23]:
arr.sum(axis=0)

array([-0.95531725, -3.14966323,  1.17022838, -1.98774972])

In [24]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [25]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [27]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

4.3.3 布尔数组的方法

In [29]:
arr = np.random.randn(100)
(arr > 0).sum()

44

In [30]:
bools = np.array([False, False, True, False])

In [31]:
bools.any()

True

In [32]:
bools.all()

False

4.3.4 排序

In [33]:
arr = np.random.randn(6)
arr

array([-0.04243118,  1.31272103, -0.15952752,  1.82042122, -0.87090006,
       -1.23895814])

In [34]:
arr.sort()
arr

array([-1.23895814, -0.87090006, -0.15952752, -0.04243118,  1.31272103,
        1.82042122])

In [47]:
arr = np.random.randn(5, 3)
arr

array([[ 1.45604902,  0.21834544, -0.09945093],
       [ 0.0764559 , -0.13223699,  0.78791984],
       [-0.46679958, -0.17095349,  0.65888603],
       [ 0.01170395, -0.85674073, -2.31334494],
       [-3.03854606, -0.9848735 , -0.43886363]])

In [48]:
arr.sort(1)
arr

array([[-0.09945093,  0.21834544,  1.45604902],
       [-0.13223699,  0.0764559 ,  0.78791984],
       [-0.46679958, -0.17095349,  0.65888603],
       [-2.31334494, -0.85674073,  0.01170395],
       [-3.03854606, -0.9848735 , -0.43886363]])

In [49]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] 

-1.776270159401759

4.3.5 唯一值与其他集合逻辑

In [50]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [51]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [52]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [53]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])