In [3]:
import numpy as np
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
x @ np.ones(3)

array([ 6., 15.])

In [16]:
from numpy.linalg import inv,qr
X = np.random.randn(5,5)
mat = X.T.dot(X)
mat

array([[ 3.43168812, -0.34935033, -0.54902406,  0.9993765 ,  0.47333603],
       [-0.34935033,  1.00037893,  1.46918867, -1.03291549, -0.68820868],
       [-0.54902406,  1.46918867,  4.90576451, -0.24554977, -2.54906889],
       [ 0.9993765 , -1.03291549, -0.24554977, 10.77575104, -2.54094436],
       [ 0.47333603, -0.68820868, -2.54906889, -2.54094436,  2.68345954]])

In [17]:
inv(mat)

array([[ 3.31285638e-01, -1.34353566e-03, -7.26227156e-02,
        -8.06409849e-02, -2.04124047e-01],
       [-1.34353566e-03,  2.28870716e+00, -3.90898858e-01,
         3.36682318e-01,  5.34685533e-01],
       [-7.26227156e-02, -3.90898858e-01,  6.92740787e-01,
         1.53982223e-01,  7.16410731e-01],
       [-8.06409849e-02,  3.36682318e-01,  1.53982223e-01,
         2.50112037e-01,  4.83670434e-01],
       [-2.04124047e-01,  5.34685533e-01,  7.16410731e-01,
         4.83670434e-01,  1.68430133e+00]])

In [18]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  5.58406281e-17, -1.54630894e-18,
         7.86649273e-17,  3.61939161e-17],
       [-4.90039473e-17,  1.00000000e+00, -1.75237075e-16,
        -3.11551193e-16, -7.51663033e-16],
       [-9.02160714e-17, -3.08305623e-16,  1.00000000e+00,
         2.71312138e-17, -7.71420589e-16],
       [-1.12147179e-17,  4.34631795e-16,  8.77639204e-16,
         1.00000000e+00,  1.83122932e-15],
       [-4.39952260e-17,  3.98298989e-17,  3.42806899e-16,
         1.59602592e-16,  1.00000000e+00]])

In [21]:
q, r = qr(mat)


In [22]:
r

array([[-3.66370806,  1.01345123,  1.78581   , -3.68247745, -0.54455369],
       [ 0.        , -1.94801982, -4.65453834,  3.7950986 ,  1.67822392],
       [ 0.        ,  0.        , -2.86891453, -8.64468316,  3.90694139],
       [ 0.        ,  0.        ,  0.        , -4.6909712 ,  1.48995609],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.5056178 ]])